// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ArchLens.Notification.Tests.BDD.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SegurancaDaAPIDeNotificacoesFeature : object, Xunit.IClassFixture<SegurancaDaAPIDeNotificacoesFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Seguranca da API de Notificacoes", "  Como um desenvolvedor\n  Quero garantir que os headers de seguranca e correlacao" +
                " estejam presentes\n  Para proteger a aplicacao contra ataques comuns e rastrear " +
                "requisicoes", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Seguranca.feature"
#line hidden
        
        public SegurancaDaAPIDeNotificacoesFeature(SegurancaDaAPIDeNotificacoesFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Headers de seguranca devem estar presentes nas respostas")]
        [Xunit.TraitAttribute("FeatureTitle", "Seguranca da API de Notificacoes")]
        [Xunit.TraitAttribute("Description", "Headers de seguranca devem estar presentes nas respostas")]
        public async System.Threading.Tasks.Task HeadersDeSegurancaDevemEstarPresentesNasRespostas()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Headers de seguranca devem estar presentes nas respostas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("que a API de Notificacoes esta em execucao", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 9
    await testRunner.WhenAsync("eu faco uma requisicao GET para \"/health\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 10
    await testRunner.ThenAsync("a resposta deve conter o header \"X-Content-Type-Options\" com valor \"nosniff\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
#line 11
    await testRunner.AndAsync("a resposta deve conter o header \"X-Frame-Options\" com valor \"DENY\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 12
    await testRunner.AndAsync("a resposta deve conter o header \"X-XSS-Protection\" com valor \"0\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 13
    await testRunner.AndAsync("a resposta deve conter o header \"Referrer-Policy\" com valor \"strict-origin-when-c" +
                        "ross-origin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 14
    await testRunner.AndAsync("a resposta deve conter o header \"Cache-Control\" com valor \"no-store\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Header Permissions-Policy deve estar presente")]
        [Xunit.TraitAttribute("FeatureTitle", "Seguranca da API de Notificacoes")]
        [Xunit.TraitAttribute("Description", "Header Permissions-Policy deve estar presente")]
        public async System.Threading.Tasks.Task HeaderPermissions_PolicyDeveEstarPresente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Header Permissions-Policy deve estar presente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 16
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
    await testRunner.GivenAsync("que a API de Notificacoes esta em execucao", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 18
    await testRunner.WhenAsync("eu faco uma requisicao GET para \"/health\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 19
    await testRunner.ThenAsync("a resposta deve conter o header \"Permissions-Policy\" com valor \"camera=(), microp" +
                        "hone=(), geolocation=()\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Correlation ID deve ser gerado automaticamente quando nao enviado")]
        [Xunit.TraitAttribute("FeatureTitle", "Seguranca da API de Notificacoes")]
        [Xunit.TraitAttribute("Description", "Correlation ID deve ser gerado automaticamente quando nao enviado")]
        public async System.Threading.Tasks.Task CorrelationIDDeveSerGeradoAutomaticamenteQuandoNaoEnviado()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Correlation ID deve ser gerado automaticamente quando nao enviado", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 22
    await testRunner.GivenAsync("que a API de Notificacoes esta em execucao", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 23
    await testRunner.WhenAsync("eu faco uma requisicao GET para \"/health\" sem correlation id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 24
    await testRunner.ThenAsync("a resposta deve possuir o header \"X-Correlation-Id\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
#line 25
    await testRunner.AndAsync("o valor do header \"X-Correlation-Id\" deve ser um GUID valido", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Correlation ID enviado pelo cliente deve ser preservado na resposta")]
        [Xunit.TraitAttribute("FeatureTitle", "Seguranca da API de Notificacoes")]
        [Xunit.TraitAttribute("Description", "Correlation ID enviado pelo cliente deve ser preservado na resposta")]
        public async System.Threading.Tasks.Task CorrelationIDEnviadoPeloClienteDeveSerPreservadoNaResposta()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Correlation ID enviado pelo cliente deve ser preservado na resposta", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 28
    await testRunner.GivenAsync("que a API de Notificacoes esta em execucao", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 29
    await testRunner.AndAsync("que eu envio o header \"X-Correlation-Id\" com valor \"test-correlation-123\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 30
    await testRunner.WhenAsync("eu faco uma requisicao GET para \"/health\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 31
    await testRunner.ThenAsync("a resposta deve conter o header \"X-Correlation-Id\" com valor \"test-correlation-12" +
                        "3\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Endpoint protegido deve exigir autenticacao")]
        [Xunit.TraitAttribute("FeatureTitle", "Seguranca da API de Notificacoes")]
        [Xunit.TraitAttribute("Description", "Endpoint protegido deve exigir autenticacao")]
        public async System.Threading.Tasks.Task EndpointProtegidoDeveExigirAutenticacao()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Endpoint protegido deve exigir autenticacao", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
    await testRunner.GivenAsync("que a API de Notificacoes esta em execucao", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 35
    await testRunner.AndAsync("que o usuario nao esta autenticado", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 36
    await testRunner.WhenAsync("eu faco uma requisicao GET para \"/hubs/analysis/negotiate?negotiateVersion=1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 37
    await testRunner.ThenAsync("o status da resposta deve ser 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await SegurancaDaAPIDeNotificacoesFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await SegurancaDaAPIDeNotificacoesFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
